name: Build and Deploy
on:
  push
    branches:
      -master
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissionsL
      contents: write
    setps:
      - name: Checkout
        uses: actions/checkout@2.3.1
        